package com.enviro.assessment.grad001.WanewaNetshodwe.Models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
public class WasteCategory {
    @Id
    @NotEmpty
    private  String id;
    @NotEmpty
    private String name;

    @OneToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
    @JoinColumn(name = "DisposalGuideLines_fk",nullable = false)
    @NotNull
    @Valid
    private DisposalGuidelines disposalGuidelines;
    @NotEmpty
    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @Valid
    private List<RecyclingTip> recyclingTips = new ArrayList<>();

    @Schema(nullable = true,hidden = true,$comment = "Auto Generated By The Server")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        return "id : "+id+ " Guidelines :"+disposalGuidelines + " Recyling Tips : "+ recyclingTips + " created at "+ createdAt;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public DisposalGuidelines getDisposalGuidelines() {
        return disposalGuidelines;
    }

    public void setDisposalGuidelines(DisposalGuidelines disposalGuidelines) {
        this.disposalGuidelines = disposalGuidelines;
    }

    public List<RecyclingTip> getRecyclingTips() {
        return recyclingTips;
    }

    public void setRecyclingTips(List<RecyclingTip> recyclingTips) {
        this.recyclingTips = recyclingTips;
    }
}
